---
# DON'T EDIT THE CONFIG VERSION VALUE!
config-version: 2

# Restart configuration
# Put the executable file name to start the server.
# Example:
# - Windows should be "start.cmd"
# - Other platform should be "start.sh"
restart:
  file-name: "start.sh"

# Settings related to Poggit Plugin Downloader
poggit:
  # Maximum time (in seconds) allowed to fetch the plugins list from Poggit.
  # Increase this parameter if your internet speed is slow.
  timeout: 30
  # ServerTools saves the plugins list from Poggit to permit the next time a fast search.
  # This parameter allow to save the plugin list after 24 hours.
  invalidate-cache: 24

# =========== WARNING ===========
# Some functions of the plugin are very dangerous if given to all the operators of your server,
# because they could cause irreparable damage. To avoid this, the plugin disables the use of
# these functions and to be enabled you need to use a third-party plugin
# for managing permissions (e.g. PurePerms or similar) and add to yourself or whoever you trust
# the permissions of the various features of you need.
# However, at your own risk, enabling the underlying setting will allow all operators
# to be able to use the plugin functions.
op-bypass-permissions: false
...